fix release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,10 +35,10 @@ jobs:
           echo "tag=$(git tag -l | grep -v -E '^.*-hotfix\..*$' | sed '/-/!{s/$/_/;}' \
             | sort -V | sed 's/_$//' | tail -1)" >> "$GITHUB_OUTPUT"
 
-      - name: Check Prerelease Version
+      - name: Check Pervious Version
         run: |
-          if ! [[ ${{ steps.latest-tag.outputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+\-rc\.[0-9]+$ ]]; then
-            echo "Invalid Prerelease Version"
+          if ! [[ ${{ steps.latest-tag.outputs.tag }} =~ ^v[0-9]+\.[0-9]+\.[0-9] ]]; then
+            echo "Invalid Pervious Version"
             exit 1
           fi
       
